apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-sxg7
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0040-tenant/tkrw-pr712-0075-0040-app/devfile-sample-sxg7@sha256:5240d4c91e86f67eac342e6072540498eb2a53a4f5cb814e8b056a175009e53c
        name: my-nodejs
        resources: {}
status: {}
